allowBuilds:
  '@firebase/util': true
  electron-winstaller: set this to true or false
  esbuild: true
  protobufjs: true
patchedDependencies:
  trystero: patches/trystero.patch
verifyDepsBeforeRun: false
